// Public half of the OTA signing key. Generated by tools/ota_tool.py keygen: do not edit.
// Placeholder: no key has been generated yet. This build cannot pull updates, and uploads in the
// web UI are not signature checked (upload a gzip-compressed firmware.bin, see README).
#ifndef OTA_PUBKEY_H
#define OTA_PUBKEY_H

#define OTA_PUBKEY_SET 0

static const uint8_t OTA_PUBKEY_N[] PROGMEM = { 0x00 };
static const uint8_t OTA_PUBKEY_E[] PROGMEM = { 0x00 };

#endif // OTA_PUBKEY_H
