"""PNG <-> PROGMEM C array conversion and bitmaps.h handling (no GUI dependencies)."""

from dataclasses import dataclass
from pathlib import Path
import json
import os
import re

from PIL import Image

Bitmap = list  # list[list[bool]], indexed [row][col]; True = pixel on

HEADER_BANNER = (
    "// WeatherWise Bedside Display — Bitmaps\n"
    "// Generated by tools/png_to_bitmap.py: edit the artwork with that tool rather than by hand.\n"
)

NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


class ConvertError(ValueError):
    """Raised for problems the user can fix (bad name, unreadable image, ...)."""


def check_name(name: str) -> str:
    """Return `name` without a trailing _bmp, or raise if it is not a usable C identifier."""
    base = name[:-4] if name.endswith("_bmp") else name
    if not NAME_RE.match(base):
        raise ConvertError(
            f"'{name}' is not a valid bitmap name: use lower-case letters, digits and underscores, "
            "starting with a letter"
        )
    return base


@dataclass
class Entry:
    """One array of a bitmaps.h file."""
    name: str          # full C name, e.g. "sun_bmp"
    pixels: Bitmap
    comment: str = ""  # text after "// name  WxH" when the tool wrote the line
    header: str = ""   # the whole comment line above the array, kept verbatim when the file is rewritten

    @property
    def width(self) -> int:
        return len(self.pixels[0]) if self.pixels else 0

    @property
    def height(self) -> int:
        return len(self.pixels)


class Converter:
    @staticmethod
    def load_png(path: str, threshold: int = 128, invert: bool = False) -> Bitmap:
        """Load an image and reduce it to 1 bit.

        Transparent pixels (alpha < 128) are "off". Other pixels are "on" when their brightness is
        at least `threshold`; `invert` flips that, for dark artwork on a light background.
        """
        with Image.open(path) as source:
            rgba = source.convert("RGBA")
        w, h = rgba.size
        gray = rgba.convert("L")
        gray_px = gray.tobytes()
        alpha_px = rgba.getchannel("A").tobytes()
        bitmap = []
        for y in range(h):
            row = []
            for x in range(w):
                i = y * w + x
                on = gray_px[i] >= threshold
                if invert:
                    on = not on
                row.append(bool(on and alpha_px[i] >= 128))
            bitmap.append(row)
        return bitmap

    @staticmethod
    def to_c_array(bitmap: Bitmap, name: str, comment: str = "", header: str = "") -> str:
        """Convert a 2D bool array to a PROGMEM C array string (Adafruit GFX byte order).

        `name` may be given with or without the _bmp suffix; the array is called <name>_bmp.
        """
        if not bitmap:
            return ""
        base = check_name(name)
        h = len(bitmap)
        w = len(bitmap[0])
        # Row-major, MSB = leftmost pixel, rows padded to full bytes
        bytes_per_row = (w + 7) // 8
        byte_data = []
        for row in bitmap:
            for byte_idx in range(bytes_per_row):
                byte_val = 0
                for bit in range(8):
                    px = byte_idx * 8 + bit
                    if px < w and row[px]:
                        byte_val |= (1 << (7 - bit))
                byte_data.append(byte_val)

        head = f"// {header}" if header else f"// {base}  {w}x{h}" + (f" {comment}" if comment else "")
        lines = [head, f"const uint8_t PROGMEM {base}_bmp[] = {{"]
        for i in range(0, len(byte_data), 12):
            chunk = byte_data[i: i + 12]
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
        lines.append("};")
        lines.append(f"#define {base.upper()}_BMP_W  {w}")
        lines.append(f"#define {base.upper()}_BMP_H  {h}")
        return "\n".join(lines)

    @staticmethod
    def parse_entries(text: str, problems: list = None) -> list:
        """Parse the PROGMEM arrays of a bitmaps.h text into Entry objects, in file order.

        Arrays that cannot be decoded are skipped and described in `problems` (if given).
        """
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        widths = {m.group(1): int(m.group(2)) for m in re.finditer(r"#define\s+(\w+)_BMP_W\s+(\d+)", text)}
        heights = {m.group(1): int(m.group(2)) for m in re.finditer(r"#define\s+(\w+)_BMP_H\s+(\d+)", text)}
        pattern = re.compile(
            r"(?://[ \t]*(?P<header>[^\n]*)\n)?"
            r"[ \t]*const\s+uint8_t\s+PROGMEM\s+(?P<name>\w+)\[\]\s*=\s*\{(?P<data>.*?)\};",
            re.DOTALL,
        )
        entries = []
        for match in pattern.finditer(text):
            name = match.group("name")
            key = name[:-4].upper() if name.endswith("_bmp") else name.upper()
            if key not in widths or key not in heights:
                if problems is not None:
                    problems.append(f"{name}: no matching #define {key}_BMP_W/_H")
                continue
            w, h = widths[key], heights[key]
            body = re.sub(r"//[^\n]*", "", match.group("data"))   # drop comments inside the array
            try:
                byte_list = [int(x.strip(), 16) for x in body.split(",") if x.strip()]
            except ValueError:
                if problems is not None:
                    problems.append(f"{name}: unreadable byte values")
                continue
            bytes_per_row = (w + 7) // 8
            if len(byte_list) != bytes_per_row * h:
                if problems is not None:
                    problems.append(f"{name}: expected {bytes_per_row * h} bytes, got {len(byte_list)}")
                continue
            pixels = []
            for row_idx in range(h):
                row = []
                for col in range(w):
                    byte_val = byte_list[row_idx * bytes_per_row + col // 8]
                    row.append(bool(byte_val & (1 << (7 - col % 8))))
                pixels.append(row)
            entries.append(Entry(name, pixels, header=(match.group("header") or "").strip()))
        return entries

    @staticmethod
    def parse_bitmaps_h(path: str, problems: list = None) -> dict:
        """Parse an existing bitmaps.h and return {array name: 2D bool array}."""
        text = Path(path).read_text(encoding="utf-8")
        return {e.name: e.pixels for e in Converter.parse_entries(text, problems)}


def render_header(entries: list) -> str:
    """Render a complete bitmaps.h from Entry objects (canonical formatting, given order)."""
    blocks = [
        Converter.to_c_array(e.pixels, e.name, e.comment, e.header) for e in entries
    ]
    return (
        HEADER_BANNER
        + "\n#ifndef BITMAPS_H\n#define BITMAPS_H\n\n#include <stdint.h>\n#include <pgmspace.h>\n\n"
        + "\n\n".join(blocks)
        + "\n\n#endif // BITMAPS_H\n"
    )


def write_atomic(path, text: str, backup: bool = True) -> None:
    """Write `text` to `path` through a temp file; keep the previous version as <path>.bak."""
    path = Path(path)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    if backup and path.exists():
        bak = path.with_name(path.name + ".bak")
        bak.write_bytes(path.read_bytes())
    os.replace(tmp, path)


def parse_slot_size(size: str) -> tuple:
    """'64×30' -> (64, 30)"""
    w, h = re.split(r"[×x]", size)
    return int(w), int(h)


def upsert_entry(existing: list, new: Entry) -> tuple:
    """Replace the entry with the same name (keeping its position) or append. Returns (list, replaced)."""
    out, replaced = [], False
    for e in existing:
        if e.name == new.name:
            # keep the old description line unless the size changed (then it would be misleading)
            same_size = (e.width, e.height) == (new.width, new.height)
            out.append(Entry(new.name, new.pixels, new.comment or e.comment, e.header if same_size and not new.comment else ""))
            replaced = True
        else:
            out.append(e)
    if not replaced:
        out.append(new)
    return out, replaced


def save_png(bitmap: Bitmap, path) -> None:
    """Write a 1-bit bitmap as a white-on-black PNG (the format `load_png` reads back losslessly)."""
    h = len(bitmap)
    w = len(bitmap[0]) if h else 0
    img = Image.new("L", (w, h), 0)
    img.putdata([255 if px else 0 for row in bitmap for px in row])
    img.save(path)


def export_assets(header_path, out_dir) -> Path:
    """Bootstrap the asset sources: write one PNG per array of an existing bitmaps.h plus a manifest."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    entries = Converter.parse_entries(Path(header_path).read_text(encoding="utf-8"))
    assets = {}
    for e in entries:
        base = check_name(e.name)
        save_png(e.pixels, out_dir / f"{base}.png")
        assets[base] = {"png": f"{base}.png", "header": e.header}
    manifest = out_dir / "manifest.json"
    manifest.write_text(
        json.dumps({"output": os.path.relpath(header_path, out_dir).replace(os.sep, "/"),
                    "threshold": 128, "assets": assets}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return manifest


def regenerate(manifest_path, out_path=None, check_only: bool = False) -> bool:
    """Rebuild bitmaps.h from PNG files listed in a JSON manifest.

    manifest: {"output": "firmware/include/bitmaps.h", "threshold": 128, "invert": false,
               "assets": {"sun": {"png": "assets/sun.png", "comment": "Sun icon"}, ...}}
    Paths are relative to the manifest. Returns True if the file is (now) up to date; with
    `check_only` it never writes and returns False when the header would change.
    """
    manifest_path = Path(manifest_path)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    base = manifest_path.parent
    threshold = int(manifest.get("threshold", 128))
    entries = []
    for name, spec in manifest["assets"].items():
        if isinstance(spec, str):
            spec = {"png": spec}
        bitmap = Converter.load_png(str(base / spec["png"]), threshold, bool(spec.get("invert", manifest.get("invert", False))))
        entries.append(Entry(check_name(name) + "_bmp", bitmap, spec.get("comment", ""), spec.get("header", "")))
    text = render_header(entries)
    out = Path(out_path) if out_path else base / manifest.get("output", "bitmaps.h")
    current = out.read_text(encoding="utf-8") if out.exists() else None
    if current == text:
        return True
    if check_only:
        return False
    write_atomic(out, text)
    return True
