"""Signing tools for pull-based OTA updates (see plans/ota_plan.md).

    python tools/ota_tool.py keygen [--private ota_private.pem]
        Creates the RSA-2048 signing key pair once. The private key stays out of git (put it in the
        GitHub secret OTA_SIGNING_KEY); the public key is written to firmware/include/ota_pubkey.h,
        which must be committed so that firmware builds can verify updates.

    python tools/ota_tool.py check-key --key KEY
        Fails unless KEY is the private half of the public key in firmware/include/ota_pubkey.h
        (devices would reject everything signed with any other key).

    python tools/ota_tool.py sign --key KEY --in firmware.bin --out motoclock-rider.bin.gz
        Gzip-compresses the image (the 1 MB ESP-01 only has room for a compressed update; the
        bootloader unpacks it) and appends the signature in the ESP8266 core's format:
        gzip image | RSA PKCS#1 v1.5 signature of SHA-256(gzip image) | uint32 LE signature length.

    python tools/ota_tool.py manifest --key KEY --version X.Y.Z --out ota-manifest.txt \\
            --variant rider=motoclock-rider.bin.gz [--variant kids=...] [--notes TEXT]
        Writes the release manifest: line 1 is compact JSON, line 2 the hex signature of line 1.
        Each variant lists the signed file to download, its size and the SHA-256 of its signed
        part, which binds the image to this (signed) version so an older signed image cannot be
        passed off as a newer one.

    python tools/ota_tool.py check-size --in firmware.bin --ldscript eagle.flash.1m64.ld
        Fails when the signed, compressed image would not fit in the flash that is free next to a
        running image of the same size (the device must have room for the next update).

Files are served from one base URL: <base>/ota-manifest.txt and <base>/vX.Y.Z/<file>
(see tools/ota-relay).
"""
import argparse
import gzip
import hashlib
import json
import re
import struct
import sys
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

ROOT = Path(__file__).resolve().parents[1]
PUBKEY_HEADER = ROOT / "firmware" / "include" / "ota_pubkey.h"
VERSION_RE = re.compile(r"^\d{1,5}\.\d{1,5}\.\d{1,5}$")
FILE_RE = re.compile(r"^[A-Za-z0-9._-]{1,48}$")
VARIANTS = ("rider", "kids")
# Flash before the filesystem (_FS_start - 0x40200000) of the 1 MB ESP8266 linker scripts
SKETCH_AREA = {
    "eagle.flash.1m64.ld": 0xEB000,
    "eagle.flash.1m128.ld": 0xDB000,
    "eagle.flash.1m256.ld": 0xBB000,
}
SECTOR = 0x1000
NOTES_MAX = 300   # the device keeps the notes in RAM


def load_private_key(path):
    key = serialization.load_pem_private_key(Path(path).read_bytes(), password=None)
    if not isinstance(key, rsa.RSAPrivateKey) or key.key_size != 2048:
        raise SystemExit("the signing key must be an RSA-2048 private key")
    return key


def sign_bytes(key, data):
    return key.sign(data, padding.PKCS1v15(), hashes.SHA256())


def signed_image(key, image, compress=True):
    if compress:
        image = gzip.compress(image, compresslevel=9, mtime=0)
    signature = sign_bytes(key, image)
    return image + signature + struct.pack("<I", len(signature))


def signed_part(signed):
    """The bytes the device hashes and verifies: everything before the signature"""
    if len(signed) < 4:
        raise ValueError("not a signed image")
    (sig_len,) = struct.unpack("<I", signed[-4:])
    if sig_len != 256 or len(signed) < sig_len + 4:
        raise ValueError("not a signed image (expected an RSA-2048 signature)")
    return signed[:-(sig_len + 4)]


def c_bytes(name, data):
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    return f"static const uint8_t {name}[] PROGMEM = {{\n" + "\n".join(rows) + "\n};\n"


def pubkey_header(public_key):
    """The raw RSA key (big-endian modulus and exponent), as BearSSL's verifier takes it"""
    numbers = public_key.public_numbers()
    n = numbers.n.to_bytes(public_key.key_size // 8, "big")
    e = numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, "big")
    return (
        "// Public half of the OTA signing key. Generated by tools/ota_tool.py keygen: do not edit.\n"
        "// Updates are only installed when their signature verifies against this key.\n"
        "#ifndef OTA_PUBKEY_H\n"
        "#define OTA_PUBKEY_H\n"
        "\n"
        "#define OTA_PUBKEY_SET 1\n"
        "\n"
        "// RSA-2048 modulus\n"
        + c_bytes("OTA_PUBKEY_N", n) +
        "// RSA public exponent\n"
        + c_bytes("OTA_PUBKEY_E", e) +
        "\n"
        "#endif // OTA_PUBKEY_H\n"
    )


def build_manifest(key, version, variants, notes=""):
    """variants: {name: (download file name, signed file bytes)}"""
    if not VERSION_RE.match(version):
        raise ValueError(f"version must be X.Y.Z, got {version!r}")
    if len(notes) > NOTES_MAX:
        notes = notes[:NOTES_MAX - 3] + "..."
    payload = {"version": version, "notes": notes, "variants": {}}
    for name, (file_name, signed) in sorted(variants.items()):
        if name not in VARIANTS:
            raise ValueError(f"unknown variant {name!r}")
        if not FILE_RE.match(file_name):
            raise ValueError(f"unsafe file name {file_name!r}")
        payload["variants"][name] = {
            "file": file_name,
            "size": len(signed),
            "sha256": hashlib.sha256(signed_part(signed)).hexdigest(),
        }
    line = json.dumps(payload, separators=(",", ":"), ensure_ascii=True).encode()
    return line + b"\n" + sign_bytes(key, line).hex().encode() + b"\n"


def free_update_space(image_size, ldscript):
    """What the web upload page offers next to a running image (ESP.getFreeSketchSpace() - 4 KB)"""
    used = (image_size + SECTOR - 1) // SECTOR * SECTOR
    return max(0, (SKETCH_AREA[ldscript] - used - SECTOR) // SECTOR * SECTOR)


def cmd_check_size(args):
    if args.ldscript not in SKETCH_AREA:
        raise SystemExit(f"unknown linker script {args.ldscript!r}: add it to SKETCH_AREA")
    image = Path(args.input).read_bytes()
    update = len(gzip.compress(image, compresslevel=9, mtime=0)) + 256 + 4
    free = free_update_space(len(image), args.ldscript)
    print(f"{args.input}: {len(image)} bytes, signed update {update} bytes, free for an update {free} bytes")
    if update > free:
        raise SystemExit("the firmware is too large to be updated over the air: make it smaller")


def cmd_keygen(args):
    private_path = Path(args.private)
    if private_path.exists():
        raise SystemExit(f"{private_path} exists; refusing to overwrite a signing key")
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private_path.write_bytes(key.private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()))
    private_path.chmod(0o600)
    Path(args.header).write_text(pubkey_header(key.public_key()))
    print(f"Private key: {private_path}  (keep it safe, never commit it)")
    print(f"Public key:  {args.header}  (commit this file)")
    print("Next: add the private key as the GitHub Actions secret OTA_SIGNING_KEY, e.g.")
    print(f"  gh secret set OTA_SIGNING_KEY < {private_path}")


def cmd_check_key(args):
    key = load_private_key(args.key)
    if Path(args.header).read_text() != pubkey_header(key.public_key()):
        raise SystemExit(f"{args.header} does not hold the public half of this key "
                         "(run keygen, or commit the header that belongs to the key)")
    print("Signing key matches the committed public key")


def cmd_sign(args):
    key = load_private_key(args.key)
    Path(args.out).write_bytes(signed_image(key, Path(args.input).read_bytes(), compress=not args.no_gzip))


def cmd_manifest(args):
    key = load_private_key(args.key)
    variants = {}
    for spec in args.variant:
        name, _, path = spec.partition("=")
        if not name or not path:
            raise SystemExit(f"--variant must be name=signed-file, got {spec!r}")
        variants[name] = (Path(path).name, Path(path).read_bytes())
    Path(args.out).write_bytes(build_manifest(key, args.version, variants, args.notes))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("keygen", help="create the signing key pair")
    p.add_argument("--private", default="ota_private.pem")
    p.add_argument("--header", default=str(PUBKEY_HEADER))
    p.set_defaults(func=cmd_keygen)

    p = sub.add_parser("check-key", help="check the key against the committed public key")
    p.add_argument("--key", required=True)
    p.add_argument("--header", default=str(PUBKEY_HEADER))
    p.set_defaults(func=cmd_check_key)

    p = sub.add_parser("sign", help="sign a firmware image")
    p.add_argument("--key", required=True)
    p.add_argument("--in", dest="input", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--no-gzip", action="store_true", help="sign the raw image (only fits on larger flash)")
    p.set_defaults(func=cmd_sign)

    p = sub.add_parser("check-size", help="check that an update of this size fits")
    p.add_argument("--in", dest="input", required=True)
    p.add_argument("--ldscript", required=True)
    p.set_defaults(func=cmd_check_size)

    p = sub.add_parser("manifest", help="write the signed release manifest")
    p.add_argument("--key", required=True)
    p.add_argument("--version", required=True)
    p.add_argument("--variant", action="append", required=True)
    p.add_argument("--notes", default="")
    p.add_argument("--out", required=True)
    p.set_defaults(func=cmd_manifest)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    sys.exit(main())
